
spring:
  application:
    name: gate-way-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: counterService
            uri: lb://COUNTER-SERVICE
            predicates:
              - Path=/counter/**

server:
  port: 8080
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8083/eureka